plugins {
    id 'org.springframework.boot' version '3.2.3'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
    id("org.sonarqube") version "5.1.0.4882"
}

group = 'com.numberbox'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-devtools'
}

bootJar { enabled = false }

test {
    useJUnitPlatform()
}

sonarqube {
    properties {
        property "sonar.coverage.jacoco.xmlReportPaths",
                "${projectDir}/project/infrastructure/orm-jpa-adapter/property 'buildDir'/jacoco.xml"
    }
}
