pluginManagement {
    plugins {
        id 'org.jetbrains.kotlin.jvm' version '1.9.22'
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.5.0'
}

rootProject.name = 'NUMBERBOX-was'

include(":project")
include(":project:app")
include(":project:rest-api")

// project-bootstrap
include(":project:bootstrap")

// project-app
include(":project:app-domain")
include(":project:app-service")

// project-adapter
include(":project:infrastructure")
include(":project:infrastructure:orm-adapter")
include(":project:infrastructure:storage-adapter")
include(":project:infrastructure:email-adapter")

// project-ui
include(":project:user-interface")
include(":project:user-interface:rest-api")

// modules
include(":modules")
include(":modules:auth-control")
include(":modules:auth-engine")
include(":modules:mail-sender-control")
include(":modules:mail-sender-engine")
include(":modules:identity-verify-control")
include(":modules:identity-verify-iamport-engine")

include(":modules:system-construction")