# DB config
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://coksabumariadb.cppobulgbd5h.ap-northeast-2.rds.amazonaws.com/numberbox?characterEncoding=utf8&allowMultiQueries=true
spring.datasource.username=dywlr74
#db passwd dependency injection via vm argument
spring.datasource.password=${db_passwd}

#hwp socket server ip address
numberbox.hwpSocketIp=43.200.243.161