# DB config
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/numberbox?characterEncoding=utf8
spring.datasource.username=root
#db passwd dependency injection via vm argument
#spring.datasource.password=${db_passwd}

#hwp socket server ip address
numberbox.hwpSocketIp=localhost