# JPA Properties
spring.jpa.database=mysql
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# multipartresolver
spring.servlet.multipart.maxFileSize=15MB
spring.servlet.multipart.maxRequestSize=15MB
server.tomcat.max-http-form-post-size=15000000

#context-path setting
server.servlet.context-path=/myWasApi

# static resources path
spring.mvc.static-path-pattern=/webapp/**


#jwtSecretKey
numberbox.openaiSecretKey=${openai_secret_key}

#emailSender
numberbox.emailAddress=${email_address}
numberbox.emailPassword=${email_password}

numberbox.openaiForbiddenWord=\uADF8\uB798\uD504,\uC911\uB4F1,\uADF8,\uC218,\uC131\uC9C8,\uC5F0\uC0B0,\uB3C4\uD615,\uACC4\uC0B0,\uB9BD,\uAE30\uBCF8,\uC2DD,\uD65C\uC6A9,\uACF1\uC148,\uC815\uB9AC,\uAD00\uACC4,\uB73B,\uBE44,\uBD80,\uC758,\uC5EC\uB7EC,\uC5EC\uB7EC\uAC00\uC9C0,\uD574,\uAC01,\uD569,\uAC00\uC9C0,\uD45C,\uC218\uD559,\uAE30\uCD08,\uB2E8\uC6D0,\uC77C\uBC18,\uACC4\uC218,\uBC29\uC815\uC2DD

#tmp aws-s3-set
numberbox.s3BucketUrl=https://numberbox-bucket.s3.ap-northeast-2.amazonaws.com/

cloud.aws.s3.bucket=${s3_bucket_name}
cloud.aws.credentials.accessKey=${aws_s3_access_key}
cloud.aws.credentials.secretKey=${aws_s3_secret_key}
cloud.aws.region.static=ap-northeast-2
cloud.aws.stack.auto=false

logging.level.root=info

server.tomcat.remoteip.remote-ip-header=X-Forwarded-For
