spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:/localhost:3306/numberbox?characterEncoding=utf8&allowMultiQueries=true
    username: ${db_username}
    password: ${db_passwd}