plugins {
    id 'org.springframework.boot' version '3.2.3'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
    id 'org.jetbrains.kotlin.jvm'
}

group = 'com.numberbox'
version = '0.0.1-SNAPSHOT'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation project(":modules:auth-control")

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-devtools'

    implementation("org.springframework.boot:spring-boot-starter-data-jpa")

    //multipartResolver
    implementation group: 'commons-io', name: 'commons-io', version: '2.11.0'
    implementation group: 'commons-fileupload', name: 'commons-fileupload', version: '1.4'


    //spring-security
    implementation 'org.springframework.boot:spring-boot-starter-security'
    //jwt
    implementation 'io.jsonwebtoken:jjwt:0.9.1'
    implementation 'javax.xml.bind:jaxb-api:2.3.1'

    //mapper, UUID
    implementation "com.fasterxml.uuid:java-uuid-generator:4.0.1"
    //modelmapper
    implementation group: 'org.modelmapper', name: 'modelmapper', version: '3.1.0'
    // https://mvnrepository.com/artifact/org.apache.poi/poi-ooxml
    implementation group: 'org.apache.poi', name: 'poi-ooxml', version: '4.1.2'
    // https://mvnrepository.com/artifact/com.github.iamport/iamport-rest-client-java
    implementation group: 'com.github.iamport', name: 'iamport-rest-client-java', version: '0.2.4'
    // https://mvnrepository.com/artifact/com.squareup.retrofit2/retrofit
    implementation group: 'com.squareup.retrofit2', name: 'retrofit', version: '2.9.0'

    implementation group: 'javax.mail', name: 'mail', version: '1.4.7'

    implementation group: 'org.qlrm', name: 'qlrm', version: '3.0.4'

    // queryDsl
    implementation 'com.querydsl:querydsl-jpa:5.0.0:jakarta'
    annotationProcessor 'com.querydsl:querydsl-apt:5.0.0:jakarta'
    annotationProcessor "jakarta.annotation:jakarta.annotation-api"
    annotationProcessor "jakarta.persistence:jakarta.persistence-api"

    //aws-s3
    implementation 'org.springframework.cloud:spring-cloud-starter-aws:2.2.6.RELEASE'
    implementation "com.amazonaws:aws-java-sdk-s3:1.12.281"

    implementation 'org.json:json:20210307'

    implementation 'com.github.shin285:KOMORAN:3.3.4'
    implementation 'org.projectlombok:lombok:1.18.28'
    runtimeOnly 'com.mysql:mysql-connector-j'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    implementation 'org.projectlombok:lombok:1.18.22'
    annotationProcessor 'org.projectlombok:lombok:1.18.22'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}

bootJar {
    enabled = false
}

bootRun {
    enabled = false
}

test {
    useJUnitPlatform()
}
kotlin {
    jvmToolchain(17)
}
