version: '3'

services:
  redis-master-1:
    container_name: redis-master-1
    image: redis:latest
    restart: always
    volumes:
      - ./redis-master-1.conf:/etc/redis-master-1.conf
    command:
      redis-server /etc/redis-master-1.conf
    ports:
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
      - "7006:7006"

  redis-master-2:
    container_name: redis-master-2
    image: redis:latest
    network_mode: "service:redis-master-1"
    restart: always
    volumes:
      - ./redis-master-2.conf:/etc/redis-master-2.conf
    command:
      redis-server /etc/redis-master-2.conf

  redis-master-3:
    container_name: redis-master-3
    image: redis:latest
    network_mode: "service:redis-master-1"
    restart: always
    volumes:
      - ./redis-master-3.conf:/etc/redis-master-3.conf
    command:
      redis-server /etc/redis-master-3.conf

  redis-replica-1:
    container_name: redis-replica-1
    image: redis:latest
    network_mode: "service:redis-master-1"
    restart: always
    volumes:
      - ./redis-replica-1.conf:/etc/redis-replica-1.conf
    command:
      redis-server /etc/redis-replica-1.conf

  redis-replica-2:
    container_name: redis-replica-2
    image: redis:latest
    network_mode: "service:redis-master-1"
    restart: always
    volumes:
      - ./redis-replica-2.conf:/etc/redis-replica-2.conf
    command:
      redis-server /etc/redis-replica-2.conf

  redis-replica-3:
    container_name: redis-replica-3
    image: redis:latest
    network_mode: "service:redis-master-1"
    restart: always
    volumes:
      - ./redis-replica-3.conf:/etc/redis-replica-3.conf
    command:
      redis-server /etc/redis-replica-3.conf

