local:
  datasource:
    url: jdbc:mysql://localhost:3306/numberbox?characterEncoding=utf8
    username: root
    password: 1111
prod:
  datasource:
    url: jdbc:mysql://localhost:3306/numberbox?characterEncoding=utf8
    username: root
    password: 1111