DELETE
FROM `numberbox_tc`.`math_contents`;
-- 자체제작 수학문제
INSERT INTO `numberbox_tc`.`math_contents` (`id`, `unit_id`, `type_id`, `contents`, `contents_img`, `img_path`,
                                            `solution`, `solution_img`, `solution_img_path`, `fir_no`, `sec_no`,
                                            `thr_no`, `four_no`, `fif_no`, `multi_choice_type`, `answer`,
                                            `choice_answer`, `member_id`, `org_src_ref`, `org_src_no`, `ques_level`,
                                            `ans_exist_stts`, `contents_classify`, `org_contents_id`, `svc_posb_stts`,
                                            `sys_create_date`, `sys_update_date`, `trans_con_cnt`)
VALUES (1, 22003, 1,
        '2<table class=\"nbExpBox nbBox\" style=\"\"><tbody><tr><td class=\"nbExpTmp borderBox\" style=\"\">a+1</td></tr></tbody></table>×2<table class=\"nbExpBox nbBox\" style=\"\"><tbody><tr><td class=\"nbExpTmp borderBox\" style=\"\">a+3</td></tr></tbody></table>=64일 때, 자연수 a의 값을 구하시오.<div style=\"\"></div>',
        NULL, NULL,
        '<div style=\"\">2<table class=\"nbExpBox nbBox\" style=\"\"><tbody><tr><td class=\"nbExpTmp borderBox\" style=\"\">a+1</td></tr></tbody></table>×2<table class=\"nbExpBox nbBox\" style=\"\"><tbody><tr><td class=\"nbExpTmp borderBox\" style=\"\">a+3</td></tr></tbody></table>=64에서&nbsp;2<table class=\"nbExpBox nbBox\" style=\"\"><tbody><tr><td class=\"nbExpTmp borderBox\" style=\"\">2a+4</td></tr></tbody></table>=2<table class=\"nbExpBox nbBox\" style=\"\"><tbody><tr><td class=\"nbExpTmp borderBox\" style=\"\">6</td></tr></tbody></table>이므로&nbsp;2a+4=6&nbsp; &nbsp; &nbsp;∴ a=1</div>',
        NULL, NULL, '', '', '', '', '', 'E', '1', NULL, UNHEX('10ED5466CDA8EA4D9BC7037CB86FDB20'), NULL, 0, 2, 1, 0, 0,
        1, '2022-02-28 06:09:46', '2022-09-28 14:46:07', 0);

-- 입시 수학 문제
INSERT INTO `numberbox_tc`.`math_contents` (`id`, `unit_id`, `type_id`, `contents`, `contents_img`, `img_path`,
                                            `solution`, `solution_img`,
                                            `solution_img_path`, `fir_no`, `sec_no`, `thr_no`, `four_no`, `fif_no`,
                                            `multi_choice_type`, `answer`,
                                            `choice_answer`, `member_id`, `org_src_ref`, `org_src_no`, `ques_level`,
                                            `ans_exist_stts`,
                                            `contents_classify`, `org_contents_id`, `svc_posb_stts`, `sys_create_date`,
                                            `sys_update_date`,
                                            `trans_con_cnt`)
VALUES (4907, 31002, 3,
        '<div style=\"\"><div style=\"\"><table class=\"nb-R-BrckBox nbBox nbBrckInFrac nbConvert\" style=\"\"><tbody class=\"nb-R-Brck-Tbody\"><tr><td class=\"nb-R-BrckBase borderBox\" style=\"\"><table class=\"nbFracBox nbBox nbFracLineConvert nbConvert\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">4</td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">2<table class=\"nbExpBox nbBox\" style=\"\"><tbody><tr><td class=\"nbExpTmp borderBox\" style=\"\"><table class=\"nbRootBox nbBox\" style=\"\"><tbody><tr><td class=\"nbRootBase borderBox\" style=\"\">2</td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><table class=\"nbExpBox nbBox\" style=\"\"><tbody><tr><td class=\"borderBox nbFracExpTmp\" style=\"\">2+<table class=\"nbRootBox nbBox\" style=\"\"><tbody><tr><td class=\"nbRootBase borderBox\" style=\"\">2</td></tr></tbody></table></td></tr></tbody></table>의 값은?<br></div><div style=\"\"></div></div>',
        NULL, NULL, '', NULL, NULL,
        '<div style=\"\"><table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">1</td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">4</td></tr></tbody></table><br></div>',
        '<div style=\"\"><table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">1</td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">2</td></tr></tbody></table><br></div>',
        '<div style=\"\"> 1<br></div><div style=\"\"></div>', '<div style=\"\"> 2 </div>', '<div style=\"\"> 4</div>',
        'M', '', '⑤', UNHEX('10ED5466CDA8EA4D9BC7037CB86FDB20'), NULL, 0, 3, 1, 4, 0, 1, '2023-01-19 23:14:52',
        '2023-01-19 23:14:52', 0)
     , (4908, 32001, 2,
        '<div style=\"\"><div style=\"\"><table class=\"nbLimBox nbBox\" style=\"\"><tbody class=\"nbLimTbody\"><tr><td class=\"nbLimSign writeDisable borderBox\" style=\"\">lim</td></tr><tr><td class=\"nbLimSubBase borderBox\" style=\"\">x → ∞</td></tr></tbody></table><table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\"><table class=\"nbRootBox nbBox\" style=\"\"><tbody><tr><td class=\"nbRootBase borderBox\" style=\"\">x<table class=\"nbExpBox nbBox\" style=\"\"><tbody><tr><td class=\"nbExpTmp borderBox\" style=\"\">2</td></tr></tbody></table>-2</td></tr></tbody></table>+3x</td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">x+5</td></tr></tbody></table>의 값은?<br></div><div style=\"\"></div></div>',
        NULL, NULL, '', NULL, NULL, '<div style=\"\"> 1 </div>', '<div style=\"\"> 2 </div>',
        '<div style=\"\"> 3<br></div><div style=\"\"></div>', '<div style=\"\"> 4 </div>', '<div style=\"\"> 5</div>',
        'M', '', '④', UNHEX('10ED5466CDA8EA4D9BC7037CB86FDB20'), NULL, 0, 3, 1, 4, 0, 1, '2023-01-19 23:14:52',
        '2023-01-19 23:14:52', 0)
     , (4909, 31004, 3,
        '<div style=\"\"><div style=\"\">공비가 양수인 등비수열&nbsp;<table class=\"nb-C-BrckBox nbBox\" style=\"\"><tbody class=\"nb-C-Brck-Tbody\"><tr><td class=\"nb-C-BrckBase borderBox\" style=\"\">a<table class=\"nbSubBox nbBox\" style=\"\"><tbody><tr><td class=\"nbSubTmp borderBox\" style=\"\">n</td></tr></tbody></table></td></tr></tbody></table>이<br></div><div style=\"\" class=\"alignCenter\">a<table class=\"nbSubBox nbBox\" style=\"\"><tbody><tr><td class=\"nbSubTmp borderBox\" style=\"\">2</td></tr></tbody></table>+a<table class=\"nbSubBox nbBox\" style=\"\"><tbody><tr><td class=\"nbSubTmp borderBox\" style=\"\">4</td></tr></tbody></table>=30, a<table class=\"nbSubBox nbBox\" style=\"\"><tbody><tr><td class=\"nbSubTmp borderBox\" style=\"\">4</td></tr></tbody></table>+a<table class=\"nbSubBox nbBox\" style=\"\"><tbody><tr><td class=\"nbSubTmp borderBox\" style=\"\">6</td></tr></tbody></table>=<table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">15</td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">2</td></tr></tbody></table><br></div><div style=\"\">를 만족시킬 때, a<table class=\"nbSubBox nbBox\" style=\"\"><tbody><tr><td class=\"nbSubTmp borderBox\" style=\"\">1</td></tr></tbody></table>의 값은?<br></div><div style=\"\"></div></div>',
        NULL, NULL, '', NULL, NULL, '<div style=\"\"> 48 </div>', '<div style=\"\"> 56 </div>',
        '<div style=\"\"> 64<br></div><div style=\"\"></div>', '<div style=\"\"> 72 </div>',
        '<div style=\"\"> 80</div>', 'M', '', '①', UNHEX('10ED5466CDA8EA4D9BC7037CB86FDB20'), NULL, 0, 4, 1, 4, 0, 1,
        '2023-01-19 23:14:52',
        '2023-01-20 20:02:43', 0)
     , (4910, 32003, 2,
        '<div style=\"\"><div style=\"\">다항함수 f<table class=\"nb-R-BrckBox nbBox\" style=\"\"><tbody class=\"nb-R-Brck-Tbody\"><tr><td class=\"nb-R-BrckBase borderBox\" style=\"\">x</td></tr></tbody></table>에 대하여 함수 g<table class=\"nb-R-BrckBox nbBox\" style=\"\"><tbody class=\"nb-R-Brck-Tbody\"><tr><td class=\"nb-R-BrckBase borderBox\" style=\"\">x</td></tr></tbody></table>를<br></div><div style=\"\">&nbsp; &nbsp; &nbsp; g<table class=\"nb-R-BrckBox nbBox\" style=\"\"><tbody class=\"nb-R-Brck-Tbody\"><tr><td class=\"nb-R-BrckBase borderBox\" style=\"\">x</td></tr></tbody></table>=x<table class=\"nbExpBox nbBox\" style=\"\"><tbody><tr><td class=\"nbExpTmp borderBox\" style=\"\">2</td></tr></tbody></table>f<table class=\"nb-R-BrckBox nbBox\" style=\"\"><tbody class=\"nb-R-Brck-Tbody\"><tr><td class=\"nb-R-BrckBase borderBox\" style=\"\">x</td></tr></tbody></table><br></div><div style=\"\">라 하자. f<table class=\"nb-R-BrckBox nbBox\" style=\"\"><tbody class=\"nb-R-Brck-Tbody\"><tr><td class=\"nb-R-BrckBase borderBox\" style=\"\">2</td></tr></tbody></table>=1, f ʹ<table class=\"nb-R-BrckBox nbBox\" style=\"\"><tbody class=\"nb-R-Brck-Tbody\"><tr><td class=\"nb-R-BrckBase borderBox\" style=\"\">2</td></tr></tbody></table>=3일 때, gʹ<table class=\"nb-R-BrckBox nbBox\" style=\"\"><tbody class=\"nb-R-Brck-Tbody\"><tr><td class=\"nb-R-BrckBase borderBox\" style=\"\">2</td></tr></tbody></table>의 값은?<br></div></div>',
        NULL, NULL, '', NULL, NULL, '<div style=\"\"> 12 </div>', '<div style=\"\"> 14 </div>',
        '<div style=\"\"> 16<br></div><div style=\"\"></div>', '<div style=\"\"> 18 </div>',
        '<div style=\"\"> 20</div>', 'M', '', '③', UNHEX('10ED5466CDA8EA4D9BC7037CB86FDB20'), NULL, 0, 4, 1, 4, 0, 1,
        '2023-01-19 23:14:52',
        '2023-01-20 20:03:02', 0)
     , (4911, 31003, 2,
        '<div style=\"\"><div style=\"\"><table class=\"nbTrigonBox nbBox\" style=\"\"><tbody><tr><td class=\"nbTrigon writeDisable borderBox\" style=\"\">tan</td></tr></tbody></table>θ &lt; 0이고&nbsp;<table class=\"nbTrigonBox nbBox\" style=\"\"><tbody><tr><td class=\"nbTrigon writeDisable borderBox grayBorderBox\" style=\"\">cos</td></tr></tbody></table>&nbsp;<table class=\"nb-R-BrckBox nbBox nbBrckInFrac nbConvert\" style=\"\"><tbody class=\"nb-R-Brck-Tbody\"><tr><td class=\"nb-R-BrckBase borderBox\" style=\"\"><table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">π</td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">2</td></tr></tbody></table>+θ</td></tr></tbody></table>=<table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\"><table class=\"nbRootBox nbBox\" style=\"\"><tbody><tr><td class=\"nbRootBase borderBox\" style=\"\">5</td></tr></tbody></table></td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">5</td></tr></tbody></table>일 때,&nbsp;<table class=\"nbTrigonBox nbBox\" style=\"\"><tbody><tr><td class=\"nbTrigon writeDisable borderBox\" style=\"\">cos</td></tr></tbody></table>θ의 값은?<br></div></div>',
        NULL, NULL, '', NULL, NULL,
        '<div style=\"\"> -<table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">2<table class=\"nbRootBox nbBox\" style=\"\"><tbody><tr><td class=\"nbRootBase borderBox\" style=\"\">5</td></tr></tbody></table></td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">5</td></tr></tbody></table></div>',
        '<div style=\"\"> -<table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\"><table class=\"nbRootBox nbBox\" style=\"\"><tbody><tr><td class=\"nbRootBase borderBox\" style=\"\">5</td></tr></tbody></table></td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">5</td></tr></tbody></table></div>',
        '<div style=\"\"> 0<br></div><div style=\"\"></div>',
        '<div style=\"\"><table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\"><table class=\"nbRootBox nbBox\" style=\"\"><tbody><tr><td class=\"nbRootBase borderBox\" style=\"\">5</td></tr></tbody></table></td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">5</td></tr></tbody></table></div>',
        '<div style=\"\"><table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">2<table class=\"nbRootBox nbBox\" style=\"\"><tbody><tr><td class=\"nbRootBase borderBox\" style=\"\">5</td></tr></tbody></table></td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">5</td></tr></tbody></table></div>',
        'M', '', '⑤', UNHEX('10ED5466CDA8EA4D9BC7037CB86FDB20'), NULL, 0, 4, 1, 4, 0, 1, '2023-01-19 23:14:52',
        '2023-01-20 20:03:19', 0)
     , (4912, 32004, 3,
        '<div style=\"\"><div style=\"\">함수 f<table class=\"nb-R-BrckBox nbBox\" style=\"\"><tbody class=\"nb-R-Brck-Tbody\"><tr><td class=\"nb-R-BrckBase borderBox\" style=\"\">x</td></tr></tbody></table>=2x<table class=\"nbExpBox nbBox\" style=\"\"><tbody><tr><td class=\"nbExpTmp borderBox\" style=\"\">3</td></tr></tbody></table>-9x<table class=\"nbExpBox nbBox\" style=\"\"><tbody><tr><td class=\"nbExpTmp borderBox\" style=\"\">2</td></tr></tbody></table>+ax+5는 x=1에서 극대이고,&nbsp;</div><div style=\"\">x=b에서 극소이다. a+b의 값은? (단, a, b는 상수이다.)<br></div></div>',
        NULL, NULL, '', NULL, NULL, '<div style=\"\"> 12 </div>', '<div style=\"\"> 14 </div>',
        '<div style=\"\"> 16<br></div><div style=\"\"></div>', '<div style=\"\"> 18 </div>',
        '<div style=\"\"> 20</div>', 'M', '', '②', UNHEX('10ED5466CDA8EA4D9BC7037CB86FDB20'), NULL, 0, 4, 1, 4, 0, 1,
        '2023-01-19 23:14:52',
        '2023-01-20 20:03:34', 0)
     , (4913, 31005, 1,
        '<div style=\"\"><div style=\"\">모든 항이 양수이고 첫째항과 공차가 같은 등차수열&nbsp;<table class=\"nb-C-BrckBox nbBox\" style=\"\"><tbody class=\"nb-C-Brck-Tbody\"><tr><td class=\"nb-C-BrckBase borderBox\" style=\"\">a<table class=\"nbSubBox nbBox\" style=\"\"><tbody><tr><td class=\"nbSubTmp borderBox\" style=\"\">n</td></tr></tbody></table></td></tr></tbody></table>이<br></div><div style=\"\">&nbsp; &nbsp; &nbsp; &nbsp;<table class=\"nbSigmaSumBox nbBox\" style=\"\"><tbody class=\"nbSigmaSumTbody\"><tr><td class=\"nbSigmaSumSup borderBox\" style=\"\">15</td></tr><tr><td class=\"nbSigmaSumSign writeDisable borderBox\" style=\"\">∑</td></tr><tr><td class=\"nbSigmaSumSub borderBox\" style=\"\">k=1</td></tr></tbody></table><table class=\"nbFracBox nbBox nbFracLineConvert nbConvert\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">1</td></tr><tr><td class=\"nbDenom borderBox\" style=\"\"><table class=\"nbRootBox nbBox\" style=\"\"><tbody><tr><td class=\"nbRootBase borderBox\" style=\"\">a<table class=\"nbSubBox nbBox\" style=\"\"><tbody><tr><td class=\"nbSubTmp borderBox\" style=\"\">k</td></tr></tbody></table></td></tr></tbody></table>+<table class=\"nbRootBox nbBox\" style=\"\"><tbody><tr><td class=\"nbRootBase borderBox\" style=\"\">a<table class=\"nbSubBox nbBox\" style=\"\"><tbody><tr><td class=\"nbSubTmp borderBox\" style=\"\">k+1</td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table>=2<br></div><div style=\"\">를 만족시킬 때, a<table class=\"nbSubBox nbBox\" style=\"\"><tbody><tr><td class=\"nbSubTmp borderBox\" style=\"\">4</td></tr></tbody></table>의 값은?<br></div></div>',
        NULL, NULL, '', NULL, NULL, '<div style=\"\"> 6 </div>', '<div style=\"\"> 7 </div>',
        '<div style=\"\"> 8<br></div><div style=\"\"></div>', '<div style=\"\"> 9 </div>', '<div style=\"\"> 10</div>',
        'M', '', '④', UNHEX('10ED5466CDA8EA4D9BC7037CB86FDB20'), NULL, 0, 4, 1, 4, 0, 1, '2023-01-19 23:14:52',
        '2023-01-31 05:37:18', 0)
     , (4914, 32004, 1,
        '<div style=\"\"><div style=\"\">점 <table class=\"nb-R-BrckBox nbBox\" style=\"\"><tbody class=\"nb-R-Brck-Tbody\"><tr><td class=\"nb-R-BrckBase borderBox\" style=\"\">0, 4</td></tr></tbody></table>에서 곡선 y=x<table class=\"nbExpBox nbBox\" style=\"\"><tbody><tr><td class=\"nbExpTmp borderBox\" style=\"\">3</td></tr></tbody></table>-x+2에 그은 접선의 x절편은?<br></div><div style=\"\"></div></div>',
        NULL, NULL, '', NULL, NULL,
        '<div style=\"\"> -<table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">1</td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">2</td></tr></tbody></table></div>',
        '<div style=\"\"> -1 </div>',
        '<div style=\"\"> -<table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">3</td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">2</td></tr></tbody></table><br></div><div style=\"\"></div>',
        '<div style=\"\"> -2 </div>',
        '<div style=\"\"> -<table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">5</td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">2</td></tr></tbody></table></div>',
        'M', '', '④', UNHEX('10ED5466CDA8EA4D9BC7037CB86FDB20'), NULL, 0, 4, 1, 4, 0, 1, '2023-01-19 23:14:52',
        '2023-01-19 23:14:52', 0)
     , (4915, 31003, 3,
        '<div style=\"\"><div style=\"\">함수<br></div><div style=\"\" class=\"alignCenter\">f<table class=\"nb-R-BrckBox nbBox\" style=\"\"><tbody class=\"nb-R-Brck-Tbody\"><tr><td class=\"nb-R-BrckBase borderBox\" style=\"\">x</td></tr></tbody></table>=a-<table class=\"nbRootBox nbBox\" style=\"\"><tbody><tr><td class=\"nbRootBase borderBox\" style=\"\">3</td></tr></tbody></table><table class=\"nbTrigonBox nbBox\" style=\"\"><tbody><tr><td class=\"nbTrigon writeDisable borderBox\" style=\"\">tan</td></tr></tbody></table>2x<br></div><div style=\"\">가 닫힌구간&nbsp;<table class=\"nb-S-BrckBox nbBox nbBrckInFrac nbConvert\" style=\"\"><tbody class=\"nb-S-Brck-Tbody\"><tr><td class=\"nb-S-BrckBase borderBox\" style=\"\">-<table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">π</td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">6</td></tr></tbody></table>, b</td></tr></tbody></table>에서 최댓값 7, 최솟값 3을 가질 때,&nbsp;</div><div style=\"\">a×b의 값은? (단, a, b는 상수이다.)<br></div></div>',
        NULL, NULL, '', NULL, NULL,
        '<div style=\"\"><table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">π</td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">2</td></tr></tbody></table></div>',
        '<div style=\"\"><table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">5π</td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">12</td></tr></tbody></table></div>',
        '<div style=\"\"><table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">π</td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">3</td></tr></tbody></table><br></div><div style=\"\"></div>',
        '<div style=\"\"><table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">π</td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">4</td></tr></tbody></table></div>',
        '<div style=\"\"><table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">π</td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">6</td></tr></tbody></table></div>',
        'M', '', '③', UNHEX('10ED5466CDA8EA4D9BC7037CB86FDB20'), NULL, 0, 5, 1, 4, 0, 1, '2023-01-19 23:14:52',
        '2023-01-20 20:04:34', 0)
     , (4916, 32006, 1,
        '<div style=\"\"><div style=\"\">두 곡선 y=x<table class=\"nbExpBox nbBox\" style=\"\"><tbody><tr><td class=\"nbExpTmp borderBox\" style=\"\">3</td></tr></tbody></table>+x<table class=\"nbExpBox nbBox\" style=\"\"><tbody><tr><td class=\"nbExpTmp borderBox\" style=\"\">2</td></tr></tbody></table>, y= -x<table class=\"nbExpBox nbBox\" style=\"\"><tbody><tr><td class=\"nbExpTmp borderBox\" style=\"\">2</td></tr></tbody></table>+k와 y축으로 둘러싸인 부분의 넓이를 A, 두 곡선 y=x<table class=\"nbExpBox nbBox\" style=\"\"><tbody><tr><td class=\"nbExpTmp borderBox\" style=\"\">3</td></tr></tbody></table>+x<table class=\"nbExpBox nbBox\" style=\"\"><tbody><tr><td class=\"nbExpTmp borderBox\" style=\"\">2</td></tr></tbody></table>, y=-x<table class=\"nbExpBox nbBox\" style=\"\"><tbody><tr><td class=\"nbExpTmp borderBox\" style=\"\">2</td></tr></tbody></table>+k와 직선 x=2로 둘러싸인 부분의 넓이를 B라 하자.&nbsp;</div><div style=\"\">A=B 일 때, 상수 k의 값은? (단, 4&lt;k&lt;5)<k<5)<br></k<5)<br></div><div style=\"\"><div style=\"\"><img src=\"https://numberbox-bucket.s3.ap-northeast-2.amazonaws.com/editorImgUpld/1020231/1674212374939_87_dhukgvgYwHkCTdG.png\" alt=\"\" class=\"\" style=\"display: block; float: unset; margin-right: auto; margin-left: auto; vertical-align: unset; width: 330px; height: 392.333px;\"></div></div></div>',
        NULL, NULL, '<div style=\"\"><br></div>', NULL, NULL,
        '<div style=\"\"><table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">25</td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">6</td></tr></tbody></table></div>',
        '<div style=\"\"><table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">13</td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">3</td></tr></tbody></table></div>',
        '<div style=\"\"><table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">9</td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">2</td></tr></tbody></table><br></div><div style=\"\"></div>',
        '<div style=\"\"><table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">14</td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">3</td></tr></tbody></table></div>',
        '<div style=\"\"><table class=\"nbFracBox nbBox\" style=\"\"><tbody><tr><td class=\"nbNumer borderBox\" style=\"\">29</td></tr><tr><td class=\"nbDenom borderBox\" style=\"\">6</td></tr></tbody></table><br></div>',
        'M', '', '④', UNHEX('10ED5466CDA8EA4D9BC7037CB86FDB20'), NULL, 0, 5, 1, 4, 0, 1, '2023-01-19 23:14:52',
        '2023-03-02 00:57:09', 0);
