# DB config
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/numberbox?characterEncoding=utf8
spring.datasource.username=${db_username}
spring.datasource.password=${db_passwd}
#jwtSecretKey
numberbox.jwtSecretKey=${jwt_secret_key}
#hwp socket server ip address
numberbox.hwpSocketIp=localhost
logging.level.root=debug
