# multipartresolver
spring:
  servlet:
    multipart:
      maxFileSize: 15MB
      maxRequestSize: 15MB
  mvc:
    static-path-pattern: /webapp/**
# tomcat
server:
  servlet:
    context-path: /myWasApi
  tomcat:
    max-http-form-post-size: 15000000
    remote-ip:
      remote-ip-header: X-Forwarded-For

# security 설정
kamcci:
  auth:
    login:
      url:
        process: /login/general
        fail: /login/fail
        logout: /logout
    jwt:
      secretKey: localSecret
      email: email
      id: userUniqId
      domain: nsoohak.com
      issuer: nsoohak
      audience: user
      access-token:
        subject: nsoohakAccessToken
        validTime: 3600000 # 1000L * 60 * 60; // 1시간
      refresh-token:
        subject: nsoohakRefreshToken
        validTime: 21600000 # 1000L * 60 * 60 * 6; // 6시간
        keepValidTime: 2592000000 # 1000L * 60 * 60 * 24 * 30; // 1달 (로그인 유지 요청한 경우)


regex:
  member:
    email: ^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}$
    password: ^.*(?=^.{8,15}$)(?=.*\d)(?=.*[a-zA-Z])(?=.*[!@#$%^&+=]).*$
