# multipartresolver
spring:
  servlet:
    multipart:
      maxFileSize: 15MB
      maxRequestSize: 15MB
  mvc:
    static-path-pattern: /webapp/**
# tomcat
server:
  servlet:
    context-path: /myWasApi
  tomcat:
    max-http-form-post-size: 15000000
    remote-ip:
      remote-ip-header: X-Forwarded-For

member:
  email:
    regex: ^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}$
